// Prompts generated by Google Gemini, Data is received from CUDO (Common University Data Ontario), OUAC, and OUInfo

import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function POST(req: Request) {
  try {
    const { profile, mode } = await req.json();

    if (!profile || !mode) {
      return NextResponse.json(
        { error: "Profile and mode are required." },
        { status: 400 }
      );
    }
    const filePath = path.join(process.cwd(), "public", "data.json");
    let programBenchmarkContext = "No specific dataset entry found.";

    if (fs.existsSync(filePath)) {
      const rawData = fs.readFileSync(filePath, "utf-8");
      const parsedData = JSON.parse(rawData);
      const institutions: any[] = parsedData.institutions || [];
      const targetUni = (profile.university || "").toLowerCase().trim();
      const targetProg = (profile.program || "").toLowerCase().trim();
      const matchedInst = institutions.find((inst: any) => {
        const name = (inst.name || "").toLowerCase();
        const id = (inst.id || "").toLowerCase();
        return (
          name.includes(targetUni) ||
          targetUni.includes(name) ||
          id.includes(targetUni)
        );
      });

      if (matchedInst) {
        const programs: any[] = matchedInst.programs || [];
        const matchedProg = targetProg
          ? programs.find((p: any) => {
              const pName = (p.program_name || "").toLowerCase();
              const pId = (p.program_id || "").toLowerCase();
              return (
                pName.includes(targetProg) ||
                targetProg.includes(pName) ||
                pId.includes(targetProg)
              );
            })
          : programs[0];

        if (matchedProg) {
          programBenchmarkContext = JSON.stringify({
            universityName: matchedInst.name,
            programName: matchedProg.program_name,
            historicalMid50Range: matchedProg.historical_mid_50_range,
            cutoffMinimum: matchedProg.cutoff_minimum,
            competitivenessTier: matchedProg.competitiveness_tier,
            adjustmentSensitivity: matchedProg.adjustment_sensitivity,
            cudoEnteringDistribution: matchedProg.cudo_entering_distribution,
          });
        }
      }
    }

    const systemPrompt = `
    You are an admissions odds evaluation engine for Canadian Universities. 
    
    BENCHMARK DATASET CONTEXT FOR THIS TARGET PROGRAM:
    ${programBenchmarkContext}
    
    CRITICAL ADMISSIONS EVALUATION RULES:
    1. Compare the applicant's Top 6 average directly against the target program's historical mid-50 range.
    2. Calculate realistic ACCEPTANCE PROBABILITY ODDS (0% - 100%).
       - Waterloo CS/SE & UofT Eng with <97% Top 6 and missing/low contest scores (<60 on Euclid/CCC) MUST be assigned LOW acceptance probability odds (e.g., 10% - 35%).
    3. Align the 'tier' strictly with the estimated probability range:
       - 0% - 25%: "Low Chance" or "Reach"
       - 26% - 60%: "Moderate Chance"
       - 61% - 100%: "High Chance"
    
    MODE INSTRUCTIONS:
    - Mode: "${mode.toUpperCase()}"
    ${
      mode === "roast"
        ? "- Tone: Brutally honest, witty, sarcastic high school admissions roast."
        : "- Tone: Supportive, constructive, encouraging admissions advisor."
    }
    
    Output ONLY raw JSON matching this structure:
    {
      "estimatedMin": number, // Actual ACCEPTANCE PROBABILITY % (0-100), NOT high school grade average
      "estimatedMax": number, // Actual ACCEPTANCE PROBABILITY % (0-100), NOT high school grade average
      "tier": "High Chance" | "Moderate Chance" | "Low Chance" | "Reach",
      "reasoning": "string (2-3 concise sentences explaining the probability using dataset stats)",
      "radarMetrics": {
        "applicantTop6": number,
        "applicantContest": number,
        "applicantEC": number,
        "applicantRigor": number,
        "applicantAdjFactor": number,
        "medianTop6": number,
        "medianContest": number,
        "medianEC": number,
        "medianRigor": number,
        "medianAdjFactor": number
      }
    }
    `;
    const userContext = `
    APPLICANT PROFILE:
    Target University: ${profile.university}
    Target Program: ${profile.program}
    Applicant Pool: OUAC ${profile.applicantType}
    Calculated Top 6 Average: ${profile.top6Average}%
    Has Non-Day School (OVS/Night School): ${
      profile.hasOvsOrNightSchool ? "Yes" : "No"
    }
    
    STEM Contests:
    - Euclid: ${profile.contests?.euclid || "N/A"}
    - CSMC: ${profile.contests?.csmc || "N/A"}
    - CCC: ${profile.contests?.ccc || "N/A"}

    Courses:
    ${JSON.stringify(profile.courses || [], null, 2)}
    `;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: userContext,
      config: {
        systemInstruction: systemPrompt,
        responseMimeType: "application/json",
      },
    });

    if (!response.text) {
      throw new Error("Empty response returned from model.");
    }

    const parsedData = JSON.parse(response.text);
    return NextResponse.json(parsedData);
  } catch (error) {
    console.error("Gemini API Error:", error);
    return NextResponse.json(
      { error: "Failed to generate evaluation" },
      { status: 500 }
    );
  }
}
