// Generated by Gemini
export const PROGRAMS: string[] = [
  // Engineering & Tech
  "Architectural Engineering",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Engineering",
  "Computer Science",
  "Electrical Engineering",
  "Engineering Science / General Engineering",
  "Environmental Engineering",
  "Industrial / Systems Engineering",
  "Management Engineering",
  "Materials Science & Engineering",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Software Engineering",

  // Business & Management
  "Accounting & Financial Management",
  "Business Administration (BBA)",
  "Commerce (BCom)",
  "Economics",
  "Finance",
  "International Business",
  "Marketing",

  // Sciences & Health
  "Biochemistry",
  "Biology / Biological Sciences",
  "Biomedical Sciences",
  "Chemistry",
  "Data Science",
  "Health Sciences / Life Sciences",
  "Kinesiology",
  "Mathematics / Applied Mathematics",
  "Nursing",
  "Physics",
  "Psychology (BSc)",
  "Statistics",

  // Arts, Humanities & Social Sciences
  "Architectural Studies",
  "Communication & Media Studies",
  "Criminology",
  "Global Studies / International Relations",
  "Graphic Design / Fine Arts",
  "Political Science",
  "Psychology (BA)",
  "Public Health",
  "Sociology",
];
